<a href="https://colab.research.google.com/github/BogdanMatyushenko1/ML/blob/main/lab%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Завдання 1: Створіть одновимірний масив (вектор) зі зростаючою геометричною прогресією, де кожне наступне число більше попереднього в 2 рази, починаючи з 2, та виведіть його значення.
vector = np.array([2**i for i in range(10)])
print("Завдання 1:", vector)

Завдання 1: [  1   2   4   8  16  32  64 128 256 512]


In [ ]:
# Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими значеннями натуральних чисел, починаючи з 1, та виведіть його значення.
matrix = np.array([[1/(i + j + 1) for j in range(3)] for i in range(3)])
print("\nЗавдання 2:\n", matrix)


Завдання 2:
 [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]


In [ ]:
# Завдання 3:Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від -3 до 3 та знайдіть максимальний елемент.
matrix = np.random.uniform(-3, 3, (3, 3))
max_element = np.max(matrix)
print("\nЗавдання 3:\n", matrix, "\nМаксимальний елемент:", max_element)


Завдання 3:
 [[-1.96490925  1.82031161 -1.87434888]
 [ 2.68722783 -1.32792847  1.237462  ]
 [ 0.63554121 -2.22531225  1.51790799]] 
Максимальний елемент: 2.687227830703641


In [ ]:
# Завдання 4: Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця, менших за 0.5.
matrix = np.random.uniform(0, 1, (3, 3))
column_sums = np.sum(matrix * (matrix < 0.5), axis=0)
print("\nЗавдання 4:\n", matrix, "\nВектор-стовпчик:", column_sums)


Завдання 4:
 [[0.81518315 0.6543812  0.8894444 ]
 [0.55398739 0.86702572 0.62896194]
 [0.93600796 0.40960038 0.31061646]] 
Вектор-стовпчик: [0.         0.40960038 0.31061646]


In [ ]:
# Завдання 5: Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання та множення.
vector1 = np.random.uniform(-2, 2, 6)
vector2 = np.random.uniform(-2, 2, 6)
print("\nЗавдання 5:")
print("Сума:", vector1 + vector2)
print("Різниця:", vector1 - vector2)
print("Добуток:", vector1 * vector2)


Завдання 5:
Сума: [-0.68039177  0.15386935  1.41553025 -1.23244699  0.49128755 -0.09056565]
Різниця: [ 0.02010006 -0.93175978 -2.08823877 -2.29668219  1.32390936  2.95130881]
Добуток: [ 0.11563224 -0.21112513 -0.58925382 -0.93895588 -0.37784313 -2.17550539]


In [ ]:
# Завдання 6: Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та знайдіть їх добуток.
matrix1 = np.random.randint(1, 6, (4, 4))
matrix2 = np.random.randint(1, 6, (4, 4))
product = np.dot(matrix1, matrix2)
print("\nЗавдання 6:\n", product)



Завдання 6:
 [[49 70 35 42]
 [22 32 16 20]
 [27 42 24 23]
 [28 51 31 28]]


In [ ]:
# Завдання 7: Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.
matrix1 = np.random.randint(1, 9, (3, 2))
matrix2 = np.random.randint(1, 9, (2, 2))
product = np.dot(matrix1, matrix2)
print("\nЗавдання 7:\n", product)


Завдання 7:
 [[46 14]
 [14  4]
 [51 15]]


In [ ]:
# Завдання 8: Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 16, (2, 2))
inverse = np.linalg.inv(matrix)
print("\nЗавдання 8:\n", matrix, "\nОбернена матриця:\n", inverse)



Завдання 8:
 [[ 3 13]
 [ 1  6]] 
Обернена матриця:
 [[ 1.2 -2.6]
 [-0.2  0.6]]


In [ ]:
# Завдання 9: Створіть матрицю розміром 7x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.random.uniform(0, 1, (7, 3))
transposed = matrix.T
print("\nЗавдання 9:\n", transposed)


Завдання 9:
 [[0.47186584 0.60364347 0.67674086 0.21453286 0.88655122 0.95131168
  0.759601  ]
 [0.51645328 0.43312235 0.76768307 0.15629146 0.63060876 0.63648172
  0.00693056]
 [0.80097265 0.66131297 0.70363387 0.10934916 0.17919317 0.17420888
  0.14494771]]


In [ ]:
# Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.uniform(0, 1, (4, 1))
product = np.dot(matrix, vector)
print("\nЗавдання 10:\n", product)


Завдання 10:
 [[ 8.28221739]
 [11.26469998]
 [13.26093151]]


In [ ]:
# Завдання 11:Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
matrix = np.random.uniform(0, 1, (2, 3))
vector = np.random.uniform(0, 1, (3, 1))
product = np.dot(matrix, vector)
print("\nЗавдання 11:\n", product)




Завдання 11:
 [[0.18351038]
 [0.30353722]]


In [ ]:
# Завдання 12: Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.
matrix1 = np.random.randint(1, 11, (6, 6))
matrix2 = np.random.randint(1, 11, (6, 6))
sum_matrix = matrix1 + matrix2
print("\nЗавдання 12:\n", sum_matrix)


Завдання 12:
 [[ 5 15 15 12  8 17]
 [14 12 15 10 17  4]
 [11  8 15 14 16 18]
 [12 14  8 16 11  9]
 [10  4 11  4 16 16]
 [18 10  9 14 12  9]]


In [ ]:
# Завдання 13: Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть добуток їх елементів.
matrix1 = np.random.uniform(0, 1, (3, 3))
matrix2 = np.random.uniform(0, 1, (3, 3))
elementwise_product = matrix1 * matrix2
print("\nЗавдання 13:\n", elementwise_product)


Завдання 13:
 [[0.45348631 0.54734206 0.03781202]
 [0.26166828 0.09143468 0.42616904]
 [0.04764328 0.01210266 0.80677801]]


In [ ]:
# Завдання 14: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть суму елементів матриці, які більше за їх середнє арифметичне значення.
matrix = np.random.uniform(-5, 5, (3, 3))
mean_value = np.mean(matrix)
sum_greater = np.sum(matrix[matrix > mean_value])
print("\nЗавдання 14:\n", matrix, "\nСума елементів більше за середнє:", sum_greater)


Завдання 14:
 [[ 3.89747233  4.48498436 -0.5931174 ]
 [ 4.09109097  3.57135997  2.16543233]
 [ 3.25286869  3.40006586 -2.16760397]] 
Сума елементів більше за середнє: 22.697842183241704


In [ ]:
# Завдання 15: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найменше ціле значення в кожному рядку матриці.
matrix = np.random.uniform(0, 1, (3, 3))
min_values = np.floor(np.min(matrix, axis=1))
print("\nЗавдання 15:\n", matrix, "\nВектор-стовпчик:", min_values)


Завдання 15:
 [[0.67027351 0.48130423 0.27844569]
 [0.5457792  0.40210479 0.85844106]
 [0.41082001 0.86684294 0.85403688]] 
Вектор-стовпчик: [0. 0. 0.]
